package:
  name: py_gd
  version: "0.1.4"

build:
  number: 4

source:
    git_url: https://github.com/NOAA-ORR-ERD/py_gd.git
#    git_tag: v0.1.4
    git_tag: master

requirements:
  build:
    - python
    - libgd
    - cython
    - numpy

  run:
    - python
    - libgd
    - numpy

test:
  requires:
    - pytest
  # Python imports
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd 


#  commands:
    # need to figure out how to run the pytests...
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

#  requires:
#    - pytest

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: Public Domain
  summary: 'Pythonic wrappers for the libgd graphics rendering library'

