package:
  name: py_gd
  version: "0.1.5"

build:
  number: 0

source:
    git_url: https://github.com/NOAA-ORR-ERD/py_gd.git
    git_tag: v0.1.5
    git_tag: master

requirements:
  build:
    - python
    - libgd
    - cython
    - numpy

  run:
    - python
    - libgd
    - numpy

test:
  requires:
    - pytest
  imports:
    - py_gd
  commands:
    - py.test --pyargs py_gd 

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

about:
  home: https://github.com/NOAA-ORR-ERD/py_gd
  license: Public Domain
  summary: 'Pythonic wrappers for the libgd graphics rendering library'

