{% set name = "oil_library" %}
{% set version = "1.0.6" %}
{% set sha256 = "39bbc19bdf7ddd2737671d6b1f28a310d324cb78ab43ada2e826e37f2ac88fef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: OilLibrary-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/OilLibrary/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - sqlalchemy
        - zope.sqlalchemy >=0.7.7
        - transaction
        - awesome-slugify
        - unit_conversion
        - repoze.lru
    run:
        - python
        - numpy
        - scipy
        - sqlalchemy
        - zope.sqlalchemy >=0.7.7
        - transaction
        - awesome-slugify
        - unit_conversion
        - repoze.lru
test:
    imports:
        - oil_library
    requires:
        - pytest
    commands:
        - py.test --pyargs oil_library


about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain
    summary: Oil library and associated code used by NOAA oil spill modeling tools
