package:
    name: oil_library
    version: v1.0.4

source:
    git_url: https://srccontrol.orr.noaa.gov/gnome/OilLibrary.git
    git_tag: v1.0.4

build: 
    number: 1
# skipping so it won't be auto-built by build-all
    skip: False

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - sqlalchemy
        - zope.sqlalchemy >=0.7.7
        - transaction
        - awesome-slugify
        - unit_conversion
        - repoze.lru
    run:
        - python
        - pytest
        - testfixtures
        - numpy
        - scipy
        - sqlalchemy
        - zope.sqlalchemy >=0.7.7
        - transaction
        - awesome-slugify
        - unit_conversion
        - repoze.lru
test:
    imports:
        - oil_library
    requires:
        - pytest
    commands:
        - py.test --pyargs oil_library


about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain
    summary: Oil library and associated code used by NOAA oil spill modeling tools
