package:
    name: oil_library
    version: 0.0.2a

source:
    git_url: https://srccontrol.orr.noaa.gov/gnome/pygnome.git
    git_tag: 0.0.2a

build: 
    number: 1
    skip: True  # [py3k]

requirements:
    build:
        - python
        - numpy
        - setuptools
        - sqlalchemy
        - transaction
        - zope.sqlalchemy
        - awesome-slugify
        - unit_conversion
        - repoze.lru
    run:
        - numpy
        - python
        - sqlalchemy
        - transaction
        - zope.sqlalchemy
        - awesome-slugify
        - unit_conversion
        - repoze.lru
test:
    imports:
        - oil_library
    requires:
        - pytest
    commands:
        - py.test --pyargs oil_library


about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain
    summary: Oil library and associated code used by NOAA oil spill modeling tools