package:
    name: pygnome
    version: 0.0.2

build:
    number: 2
# skipping so it won't be auto-built by build-all
    skip: True

source:
    git_url: https://srccontrol.orr.noaa.gov/gnome/pygnome.git
    git_tag: 0.0.2

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - cython
        - py_gd
    run:
        - matplotlib
        - python
        - scipy
        - numpy
        - netcdf4
        - colander
        - pil
        - pyzmq
        - repoze.lru
        - six
        - geojson
        - gdal
        - scipy
        - unit_conversion
        - py_gd
        - oil_library
        - gsw
        - psutil

test:
    imports:
        - gnome
    requires:
        - pytest
        - progressbar
        - testfixtures
    commands:
        - cd ../work/py_gnome
        - py.test

about:
    home: https://github.com/NOAA-ORR-ERD/PyGnome
    license: Public Domain