{% set version = "0.3.4" %}
{% set sha256 = "2dfdef439159f7cdc1df66e94e856caee29e4017e5d2c5fefd1c8ee46dd01775"%}


package:
    name: pysgrid
    version: {{ version }}

source:
    fn: pysgrid-{{ version }}.tar.gz
    url: https://github.com/NOAA-ORR-ERD/pysgrid/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - netcdf4

test:
    imports:
        - pysgrid

about:
    home: https://github.com/sgrid/pysgrid
    license: BSD-3-Clause
    summary: Python package for working with staggered gridded data


# # Conda recipe example.
# package:
#     name: pysgrid
#     version: "0.3.2"

# source:
#     git_url: https://github.com/NOAA-ORR-ERD/pysgrid.git
#     git_tag: v0.3.2

# build:
#     number: 1

# requirements:
#     build:
#         - python
#         - setuptools
#     run:
#         - python
#         - numpy
#         - netcdf4
#         - scipy

# test:
#     imports:
#         - pysgrid

# about:
#     home: https://github.com/pysgrid/pysgrid
#     license: BSD
#     summary: 'A Python API to utilize data written using the unstructured grid UGRID conventions'
