{% set version = "2.2.0" %}

package:
  name: wxmpl
  version: {{ version }}

source:
  fn: wxmpl-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/wxmpl/archive/{{ version }}.tar.gz
  sha256: c16b1a7b634d7d7dc0ef1060104d293ee21c63fd6b5d19e17ee63cdd887a4126

build:
  number: 0
  noarch: python
  script: pip install --no-deps --no-cache-dir ./

requirements:
  build:
    - python <=3
    - pip

  run:
    - python <=3
    - numpy
    - wxpython
    - matplotlib

test:
  imports:
    - wxmpl

about:
  home: https://github.com/NOAA-ORR-ERD/wxmpl
  license: BSD-like
  summary: 'Painless matplotlib embedding in wxPython'
