package:
    name: obvious-ci
    version: '0.5.1'

source:
    git_url: https://github.com/pelson/Obvious-CI.git
    git_tag: v0.5.1

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - anaconda-client
        - conda
        - conda-build

about:
    home: https://github.com/pelson/Obvious-CI
    license: GPL
    summary: Simplify the implementation of continuous integration such as Travis CI and appveyor.
