package:
  name: libgd
  version: 2.1.1

build:
  number: 5
  skip: True  # [not win]

source:
  # NOTE: the source tarball has a minor bug (double ;;) that the Windows compiler
  #       chokes on -- hence pulling from git on Windows
  git_url: https://github.com/libgd/libgd # [win]
  git_branch: GD-2.1 # [win]

  # on OS-X and Linux (presumably) you want the distributed tarball
  fn: libgd-2.1.1.tar.gz # [not win]
  url: https://bitbucket.org/libgd/gd-libgd/downloads/libgd-2.1.1.tar.gz # [not win]
  # NOTE: the tarball on github does not have a configure script
  #       if you install all the autotools deps, it should work
  #       with the "bootstrap.sh" script, but this source version
  #       is easier, with a configure script ready to go
  #       the gd devs indicated that they will probably put
  #       configured source tarball on github at some point...


extra:
   recipe_maintainer : https://github.com/NOAA-ORR-ERD/py_gd

about:
    home: http://libgd.github.io/


requirements:
  build:
    - libpng
    - jpeg
    - freetype
    - zlib
    - libtiff

  run:
    - libpng
    - jpeg
    - freetype
    - zlib
    - libtiff

