package:
    name: pyugrid
    version: "0.1.7"

source:
    git_url: https://github.com/pyugrid/pyugrid.git
    git_tag: 0.1.7.1

requirements:
    build:
        - python
        - setuptools
        - netcdf4
        - matplotlib
        - scipy
        - mock
        - nose
    run:
        - python
        - numpy
        - netcdf4

test:
    imports:
        - pyugrid

about:
    home: https://github.com/pyugrid/pyugrid
    summary: A Python API to utilize data written using the unstructured grid UGRID conventions.
