# Note: this recipe simply downloads and installs the binary wheels on pypi

{% set version = "4.0.0b2" %}

package:
  name: wxpython
  version: {{ version }}

build:
  number: 0
  script: pip install wxpython=={{ version }}

python:
  - 2.7
  - 3.6

requirements:
  build:
    - python
    - setuptools
    - pip
    - six

  run:
    - python
    - six

test:
    imports:
        - wx

about:
  home: http://www.wxpython.org/
  license: wxWindows License
  summary: '*new* Python wrapper around the wxWidgets Cross platform Graphical User Interface library'
