{% set version = "0.3.0" %}

package:
    name: cell_tree2d
    version: {{ version }}

source:
    fn: cell_tree2d-{{ version }}-.tar.gz
    url: https://github.com/NOAA-ORR-ERD/cell_tree2d/archive/v{{ version }}.tar.gz
    sha256: 4a5759951f67a3ff199137c87bb565b1897541130de5a4a2067acb22b0f39bae

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x

test:
    requires:
        - pytest
    imports:
        - cell_tree2d
    commands:
        - py.test --pyargs cell_tree2d

about:
    home: https://github.com/NOAA-ORR-ERD/cell_tree2d
    license: Public Domain
    summary: CellTree data structure as described by Garth and Joy 2010



# # Conda recipe example.
# package:
#     name: cell_tree2d
#     version: "0.3.0"

# source:
#     git_url: https://github.com/NOAA-ORR-ERD/cell_tree2d
#     git_tag: v0.3.0

# build:
#     number: 0

# requirements:
#   build:
#     - python
#     - cython
#     - numpy 1.11.*

#   run:
#     - python
#     - numpy 1.11.*

# test:
#   requires:
#     - pytest
#     - python
#     - numpy

#   imports:
#     - cell_tree2d

#   commands:
#     - py.test --pyargs cell_tree2d 

#   # You can also put a file called run_test.py in the recipe that will be run
#   # at test time.


# about:
#   home: https://github.com/NOAA-ORR-ERD/cell_tree2d
#   license: Public Domain
#   summary: 'Data structure for rapid resolution of the "which polygon is this point in" question on unstructured grids'
