package:
  name: pytest-cov
  version: "2.2.1"

source:
  fn: pytest-cov-2.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pytest-cov/pytest-cov-2.2.1.tar.gz
  md5: d4c65c5561343e6c6a583d5fd29e6a63

build:
  number: 0
#  noarch_python: True


requirements:
  build:
    - python >=2.7
    - pytest >=2.6.0
    - coverage >=3.7.1

  run:
    - python >=2.7
    - pytest >=2.6.0
    - coverage >=3.7.1

test:
  # Python imports
  #imports:
    # - not sure what to import here
#  commands:
  #   - py.test --cov # if there are no tests, it returns an error code 

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT License
  summary: Coverage plugin for pytest

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
