package:
  name: regex
  version: 2016.06.24

source:
  fn: regex-2016.06.24.tar.gz
  url: https://pypi.python.org/packages/96/4a/9943cf2bc0c60e6c502c1df407393696f97ac0209794ee827cf263cbcb60/regex-2016.06.24.tar.gz
  md5: e75fcd602b73483543444e443faa4119

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - regex

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://code.google.com/p/mrab-regex-hg/
  license: Python Software Foundation License
  summary: 'Alternative regular expression module, to replace re.'
