package:
  name: regex
  version: "2014.12.24"

source:
  fn: regex-2014.12.24.tar.gz
  url: https://pypi.python.org/packages/source/r/regex/regex-2014.12.24.tar.gz
  md5: f7897fed0c7cee3fca3445222f829d8f
build:
  number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - regex

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://code.google.com/p/mrab-regex-hg/
  license: Python Software Foundation License
  summary: 'Alternative regular expression module, to replace re.'
