package:
  name: geojson
  version: "1.3.2"

source:
  fn: geojson-1.3.2.tar.gz
  url: https://pypi.python.org/packages/source/g/geojson/geojson-1.3.2.tar.gz
  md5: 27b75a4edbf9059e9aeb819eaad38593
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - geojson

#  commands:
#    - py.test
#  requires:
#    - pytest
#  files:
#    - tests/*

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD License
  summary: 'Python bindings and utilities for GeoJSON'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
