{% set version = "2.6.0" %}

package:
  name: unit_conversion
  version: {{ version }}

source:

  fn: PyNUCOS-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v{{ version }}.tar.gz
  sha256: 313e0cdcf17ecb081ccebf222b70b80a4751396552ffce8a38bcbafffddfbe81

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=2.7
    - setuptools
  run:
    - python >=2.7

test:
    imports:
      - unit_conversion
    requires:
      - pytest
    commands:
      - py.test --pyargs unit_conversion

about:
    home: https://github.com/NOAA-ORR-ERD/PyNUCOS
    license: Public Domain
    summary: 'Physical Unit conversions for Oil Spill Response'

