{% set version = "2.6.1" %}
{% set build_num = "1" %}

package:
  name: unit_conversion
  version: {{ version }}

source:

  fn: PyNUCOS-{{ version }}.tar.gz
  url: https://github.com/NOAA-ORR-ERD/PyNUCOS/archive/v{{ version }}.tar.gz
  sha256: 7693277d8df971618eb4660d3669fdcf512a004193b91936b8f8a01cddfb4b18

build:
  number: {{ build_num }}
  string: py27_{{ build_num }} # set so that noarch is clearly py27 (enforced by the run reqs)
  noarch: python

requirements:
  build:
    - python >=2.7
    - setuptools
  run:
    - python >=2.7

test:
    imports:
      - unit_conversion
    requires:
      - pytest
    commands:
      - py.test --pyargs unit_conversion

about:
    home: https://github.com/NOAA-ORR-ERD/PyNUCOS
    license: Public Domain
    summary: 'Physical Unit conversions for Oil Spill Response'

